### PR TITLE
Marketplace sample calls

### LINKED ISSUE #912: Add new samples for Marketplace, Collections and NFTs
**Summary**
We need to add samples with the new endpoints  to show how to use it in Unity, in the past we have those but using the old endpoints.

**Suggested features or ways to address the summary**
Specs:

- https://docs.gaming.chainsafe.io/marketplace-api/docs/marketplaceapi
- https://docs.gaming.chainsafe.io/token-api/docs/tokenapi
- Create collection: https://docs.gaming.chainsafe.io/launchpad/tutorial#2-create-a-collection
- Deploy marketplace: https://docs.gaming.chainsafe.io/marketplace/tutorial#2-deploy-marketplace

**Motivation**
Show devs how they can integrate they own marketplace into the ChainSafe SDK

**Acceptance Criteria**
Dev should be able to:

- Create Collection of ERC-721 type
- Create Collection of ERC-1155 type
- Get created collections
- Remove collection if transaction failed
- Retry deployment of collection if transaction failed
- Mint NFT inside collection of ERC-721 type
- Mint NFT inside collection of ERC-1155 type with custom supply
- Get minted NFTs
- Create Marketplace
- List NFTs into created Marketplace
- Get listed NFTs inside Marketplace

### PR DESCRIPTION
**Pull request by sneakzttv**
Marketplace write calls are now functional within the sample scene, these functions can easily be added to a GUI to populate it with data as the user wishes.

image

To test:
- You will need a bearer token from the dashboard login console https://dashboard.gaming.chainsafe.io/ it comes from the login response in the network tab and its member key is access_token, we need a better way to expose this to the user as it's needed for the request header with half of the calls.
- You will also need to create a 721, 1155 collection with Nfts and a marketplace to see the get calls, you can also do this from the editor if you choose.
- Insert all the details into the Marketplace Call object and fill it out with contract & id information. Be careful with IDs and contracts, they're two different things.
- As the contracts are specific to users and have role control, they need to be initialized by the person using them for functions like mint which is why i have left the variables open.
- Press play and test the marketplace functions in the sample scene.
- Newly created collections, marketplaces and minted Nfts will show up accordingly in the dashboard.
- Deleting may be sticky to test as it can only be used after chain interactions are reverted for creating collections/marketplaces.
- Server settings menu moved up a level in the editor as it's more intuitive there.

### CODE REVIEW

**Review by rob1997 — APPROVED** [review]

**Review by kantagara — APPROVED** [review]

**Comment by sneakzttv** [comment]
Updating to 2022 to gain better code coverage on this PR within the new system, will include webgl and classes update momentarily.

**Comment by sneakzttv** [comment]
Fixed, also closes #959

**Review by juans-chainsafe — CHANGES_REQUESTED** [review]
Majority of the samples are working, but some are failing. Here is the current status:

**Working**
- GetProjectItems :white_check_mark:
- GetMarketplaceItems :white_check_mark:
- GetItem :white_check_mark:
- GetProjectTokens :white_check_mark:
- GetCollectionTokens721 :white_check_mark:
- GetCollectionTokens1155
- GetCollectionToken :white_check_mark:
- GetTokenOwners :white_check_mark:
- CreateCollection721 :white_check_mark:
- CreateCollection1155 :white_check_mark:
- CreateMarketplace ✅ 

**Functionality working but I get errors**
- DeleteCollection :white_check_mark: :x:
```
NullReferenceException: Object reference not set to an instance of an object
Scripts.EVM.Remote.CSServer.DeleteData (System.String _bearerToken, System.String _path) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Remote/CSServer.cs:60)
Scripts.EVM.Marketplace.Marketplace.DeleteCollection (System.String _bearerToken, System.String _collectionId) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Marketplace/Marketplace.cs:283)
MarketplaceCalls.DeleteCollection () (at Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Marketplace/MarketplaceCalls.cs:204)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

**Failing**

- Mint721 ❌ 
- Mint 1155 ❌ 
Full log for Mint error:
```
[Web3] [WalletConnect SDK] [JsonRpcProvider] Got payload {"id":439372001364994,"jsonrpc":"2.0","method":"irn_subscription","params":{"id":"13b6432a6b7fd533950b29d25b66ce86af943bc559d989b7e5edb1f2c2e87002","data":{"topic":"7b62869c46b6c9c9b015407e455d6f8583bf7673c3fc40a130a15635a98ce19a","message":"ALH23F3Cf4j/71q2ju8NSdhu4NydT0WI5w6/PKlufQofeuCM7DhpSPtBlZKRfFYKtuxqyJeH00CC6FZ9AWhe9Ov7nvfs05I5dXoSWBnoy6vHhdBtQTf6KV81zrmvQNXOezCnH0+FSdyT95TILnh+nM4SD+2bMCVT7sUWDDFV6HADZ86ARH3yn/d8BsfteLLsNUlVlMkhk+A+cpQ5Z0wxiizPvNz4u27ReR3aKJztevrGmWhkA50vp+b+Zm40","publishedAt":1716296880237,"tag":1109}}}

[Web3] [WalletConnect SDK] [JsonRpcProvider] Payload has ID 439372001364994

[Web3] [WalletConnect SDK] Got generic response for type System.String

[Web3] [WalletConnect SDK] Got response for type System.String
 
WalletConnectException: User disapproved requested chains
WalletConnectSharp.Sign.Engine.Request[T,TR] (System.String topic, T data, System.String chainId, System.Nullable`1[T] expiry) (at <8a03767a7c084e38b9e400624d188dfb>:0)
ChainSafe.Gaming.WalletConnect.WalletConnectProvider.Request[T] (T data, System.Nullable`1[T] expiry) (at <0d45ab63aa8549c4ad1635c4b8a7792b>:0)
ChainSafe.Gaming.WalletConnect.WalletConnectTransactionExecutor.SendTransaction (ChainSafe.Gaming.Evm.Transactions.TransactionRequest transaction) (at <0d45ab63aa8549c4ad1635c4b8a7792b>:0)
ChainSafe.Gaming.Evm.Contracts.Contract.SendWithReceipt (System.String method, System.Object[] parameters, ChainSafe.Gaming.Evm.Transactions.TransactionRequest overwrite) (at <a5a8db86682c403bbecf38c48c360d65>:0)
ChainSafe.Gaming.Evm.Contracts.Contract.Send (System.String method, System.Object[] parameters, ChainSafe.Gaming.Evm.Transactions.TransactionRequest overwrite) (at <a5a8db86682c403bbecf38c48c360d65>:0)
Scripts.EVM.Token.Evm.ContractSend (ChainSafe.Gaming.Web3.Web3 web3, System.String method, System.String abi, System.String contractAddress, System.Object[] args, Nethereum.Hex.HexTypes.HexBigInteger value) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Evm.cs:26)
Scripts.EVM.Marketplace.Marketplace.Mint721CollectionNft (System.String _collectionContract, System.String _uri) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Marketplace/Marketplace.cs:234)
MarketplaceCalls.Mint721CollectionNft () (at Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/Marketplace/MarketplaceCalls.cs:184)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

- DeleteMarketplace ❌ 
`Error deleting: HTTP/1.1 404 Not Found`
But Marketplace exists and is not deployed:
```
{
    "id": "0d6419b6-ed27-4372-90d3-3ed2d183549a",
    "name": "test delete",
    "description": "",
    "owner": "6dabb083-f75d-482c-8b2b-aad3818ff93b",
    "chain_id": 11155111,
    "banner": "",
    "project_id": "6aa5af5a-cf38-4093-b78a-c1c13b58d0f4",
    "contract_address": "",
    "deployed": false,
    "created_at": 1716296563,
    "updated_at": 1716296563
}
```
Screenshot 2024-05-21 at 10 26 53 AM

**Review by juans-chainsafe — APPROVED** [review]
Issues were fixed!
Mint1155 ✅ 
WebGL ✅ 

I didnt find any more issues, awesome work! The only annoying thing is the Bearer token that expires

**Pull request merged**
