### PR TITLE
Technical debt collection

### PR DESCRIPTION
**Pull request by sneakzttv**
Fixing some issues RE: https://github.com/ChainSafe/web3.unity/issues/680

Menu items grouped for usability:
image

Report bug menu added:
image

Upload button removed from more examples:
image

Web3Builder.BuildAsync() changed to web3Builder.LaunchAsync() in all occurrences:
image

Adjust the behavior of ChainsafeServerSettings and WebGLTemplatesInstallerTool:

Removed the WebGL template sync button at server settings as the templates should be updated prior to each release and more than likely wont change. 

---------------------------------To Test---------------------------------
Boot up the SDK after running the batch file, it should open up without errors.
All of the above changes should be present and functional.

### CODE REVIEW

**Comment by sneakzttv** [comment]
should we just make it automatic when switching? not a fan of the popup for something that's necessary when in WebGL.

**Comment by sneakzttv** [comment]
reverting the template check for now as it's tricky with the editor scripts, rest should be good, just check again @juans-chainsafe

**Review by robGG1997 — APPROVED** [review]

**Review by RyRy79261 — APPROVED** [review]

**Review by juans-chainsafe — CHANGES_REQUESTED** [review]
Popup to install them appears correctly, and I see the templates in the build settings but if I try to build with WebGL I get these errors:
```
Assets/Samples/web3.unity SDK/2.5.0/Web3.Unity Samples/Scripts/Scenes/SampleMain/SampleBehaviour.cs(31,132): error CS0103: The name 'ChainSafeServerSettings' does not exist in the current context

Error building Player because scripts had compiler errors
```

**Review by juans-chainsafe — APPROVED** [review]
WebGL builds working now! I found new issues but not related to this PR

**Pull request merged**
