### PR TITLE
Chainlink - Lootboxes

### PR DESCRIPTION
**Pull request by oleksandrchainsafe**
### Lootboxes implementation using Chainlink random number generation

This PR contains:
- A new module that integrates smart contract lootbox logic from [this repo](https://github.com/ChainSafe/vrf-lootbox-contracts/tree/main).
- A sample scene for demo purposes.

Follow [this readme file](https://github.com/ChainSafe/web3.unity/blob/oleksandr/lootboxes/src/UnitySampleProject/Assets/Samples/web3.unity%20SDK/2.5.0/LootBoxes/README.md) to run demo scene.

### CODE REVIEW

**Review by juans-chainsafe — DISMISSED** [review]
Issues were fixed, all working now!

**Comment by kantagara** [comment]
@juans-chainsafe can you look at this again?

**Comment by juans-chainsafe** [comment]
> @juans-chainsafe can you look at this again?

I'm not able to run script.sh or publish-to-unity.package.sh

**Comment by juans-chainsafe** [comment]
> @juans-chainsafe can you look at this again?

On it! just something that I saw: scenes are duplicated in build settings
Screenshot 2023-09-27 at 12 16 38

**Review by juans-chainsafe — DISMISSED** [review]
Getting this error when I click Play on the Lootboxes scene:

```
Web3Exception: No ISigner was registered. Can't get current user's address.
ChainSafe.Gaming.Chainlink.Lootboxes.LootboxService.GetCurrentPlayerAddress () (at <198150e3c5714df192bdb8a766181b4d>:0)
ChainSafe.Gaming.Chainlink.Lootboxes.LootboxService.CanClaimRewards () (at <198150e3c5714df192bdb8a766181b4d>:0)
LootBoxes.Scene.States.ResetStageState.OnLootBoxSceneStateEnter () (at Assets/LootBoxes/Scripts/Scene/States/ResetStageState.cs:15)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <b6c5d0f08ddf477186f780f49bb14dee>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

**Review by juans-chainsafe — APPROVED** [review]
Error is fixed.
After we have the tests, we can merge this!

**Comment by kalambet** [comment]
To run Lootboxes test you need to run hardhat node from the `vrf-lootbox-contracts` repo and 
run `npm run hardhat -- devsetup` to prepare the chain state, after that you can run:
`dotnet test --verbosity normal /property:Lootboxes=true`

**Review by kalambet — APPROVED** [review]

**Review by robGG1997 — APPROVED** [review]

**Comment by kantagara** [comment]
Tested out lootboxes on both standalone and webGL build. If WebGL build, for any reason, doesn't build exit unity, and delete the Library folder in the SampleProject. That should do the trick (it did for me).

**Review by kantagara — APPROVED** [review]

**Review by robGG1997 — APPROVED** [review]

**Pull request merged**
