### PR TITLE
webgl load fix

### PR DESCRIPTION
**Pull request by sneakzttv**
Fixed an issue causing webgl to error out on boot.

### CODE REVIEW

**Comment by sneakzttv** [comment]
closes #367

**Review by juans-chainsafe — APPROVED** [review]
This didn't happen to me on the 2.1.0 version, maybe I need to put something specific on the Webgl build to see the error? anyways, I tried a WebGL build on this branch and is working correctly.

**Comment by sneakzttv** [comment]
you can see it happening here, just refresh it a few times https://chainsafe.github.io/ChainSafe-Demo-WebGL/ Anyway I'm still seeing this issue, don't merge this yet.

**Comment by sneakzttv** [comment]
mm its fine, needs to be in the body regardless

**Comment by KBryan** [comment]
Of course, you don't execute logic in the header.

**Pull request merged**
