### PR TITLE
Web3GL Template - Onboard.js Overhaul

### PR DESCRIPTION
**Pull request by RyRy79261**
# Changelog 

- Web3gl template has been replaced by Onboard.js
- Template is minified using Vite

### CODE REVIEW

**Review by sneakzttv — APPROVED** [review]

**Review by KBryan — APPROVED** [review]

**Review by juans-chainsafe — CHANGES_REQUESTED** [review]
The following wallets are not working:

- Crypto.com
- Wallet3
- Exodus
- Bobablocks
- Verso
Error: `Failed to launch 'cryptowallet://wc?uri=wc%3A2babb67a-2f0d-4d04-a285-a04a6c2d5bf8%401%3Fbridge%3Dhttps%253A%252F%252Fx.bridge.walletconnect.org%26key%3D73ecfb1cf0a8ad4796d41257cbf1308d871d14684ca698510e3e897e729779bf' because the scheme does not have a registered handler.`
Screenshot 2023-03-03 at 13 57 16

Also, Wallet3 is repeated in page 1 and page 2

**Comment by sneakzttv** [comment]
gj @juans-chainsafe i didn't even think to check the alternate wallets, i just checked metamask and wc, my fault there.

**Comment by RyRy79261** [comment]
@juans-chainsafe Thanks for the rigorous testing, though I'm unsure if thats within the scope of what I can do in this code base. 

Like wallet connect is a standard, so if those wallets dont implement it, then I'm not sure, it says we need a registered handler, but as far as onboard is concerned, wallet connect is wallet connect and I just specify a bridge if I want. 

@FSM1 ever seen this?

**Comment by RyRy79261** [comment]
This is the reference [set up config](https://github.com/blocknative/web3-onboard/blob/develop/packages/walletconnect/README.md)

**Comment by RyRy79261** [comment]
@juans-chainsafe 

So those links you were trying to open appear to be for opening up apps on mobile. The apps name as the protocol portion should normally deep link open the specific app.

You make reference to `Page 1 & 2` where are you seeing pages?

**Comment by juans-chainsafe** [comment]
> @juans-chainsafe
> 
> So those links you were trying to open appear to be for opening up apps on mobile. The apps name as the protocol portion should normally deep link open the specific app.
> 
> You make reference to `Page 1 & 2` where are you seeing pages?

They appear after generating a build on Unity with the WebGL template:
page 1
Screenshot 2023-03-09 at 11 44 08
page 2
Screenshot 2023-03-09 at 11 46 28

(Now Wallet3 is repeated on page 1)

- I also noticed that the Search input doesn't work

One question, in the modal says "Desktop" so why they appear there if they are meant for mobile?

**Review by juans-chainsafe — APPROVED** [review]
due that the above errors are not on our side, I approve this PR

**Review by sneakzttv — APPROVED** [review]
lets light this bad boy up

**Pull request merged**
