### PR TITLE
Show Registration

### PR DESCRIPTION
**Pull request by KBryan**
Show's registration if one hasn't been created already.

### CODE REVIEW

**Comment by sneakzttv** [comment]
wooo you found the illusive line!

**Review by sneakzttv — APPROVED** [review]
LGTM!

**Comment by sneakzttv** [comment]
do we merge and get @juans-chainsafe to update release as an edit seeing as this is so close? @KBryan

**Comment by juans-chainsafe** [comment]
All good! awesome, so I update the unity package on 1.6.1? with this fix @KBryan @sneakzttv

**Comment by KBryan** [comment]
ty

**Comment by juans-chainsafe** [comment]
1.6.1 updated!

**Pull request merged**
