### PR TITLE
CI Improvements & Optimizations

### PR DESCRIPTION
**Pull request by rob1997**
Duplicate Samples and Sync Dependencies now moved to setup.sln
Most actions are now highly configurable and can be run manually as well
Setup can be run independently with argument/flags such as `-sync_dependencies` , `-duplicate_samples` and `release:3.0.2` all together as well
Sync Branches action added that can sync branches when a push is made to main automatically, specifically dev
tests fixed and improved
Parallel runs to save some time
Can't run CI yet until merged to main but [here](https://github.com/ChainSafe/web3.unity/actions/runs/11438423351) is a successful run demo

### CODE REVIEW

**Review by kantagara — APPROVED** [review]
E P I  CCCC

**Comment by rob1997** [comment]
Reminder Updated required actions for PRs in branch protection rules

**Review by juans-chainsafe — APPROVED** [review]
Nothing to test here in the UI

**Review by creeppak — APPROVED** [review]
👍👍👍

**Pull request merged**
