### PR TITLE
Fixing iOS import

### PR DESCRIPTION
**Pull request by kantagara**

### CODE REVIEW

**Review by sneakzttv — APPROVED** [review]

**Review by juans-chainsafe — CHANGES_REQUESTED** [review]
I'm getting these errors when I try to build with iOS:

```
Assets/Tests/Erc20Tests.cs(15,6): error CS0246: The type or namespace name 'UnitySetUpAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(15,6): error CS0246: The type or namespace name 'UnitySetUp' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(35,6): error CS0246: The type or namespace name 'UnityTestAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets/Tests/Erc20Tests.cs(35,6): error CS0246: The type or namespace name 'UnityTest' could not be found (are you missing a using directive or an assembly reference?)

Error building Player because scripts had compiler errors

Build completed with a result of 'Failed' in 2 seconds (1548 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)

UnityEditor.BuildPlayerWindow+BuildMethodException: 5 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002ce] in /Users/bokken/build/output/unity/unity/Editor/Mono/BuildPlayerWindowBuildMethods.cs:193 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in /Users/bokken/build/output/unity/unity/Editor/Mono/BuildPlayerWindowBuildMethods.cs:94 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:189)
```

**Comment by sneakzttv** [comment]
I think it's unrelated as file changes were just a system include.

**Comment by kantagara** [comment]
Yeah it is unrelated but we have the same issue on main...

**Review by juans-chainsafe — APPROVED** [review]
yes, the original error was fixed, but iOS build is still not working, but if it will fixed in another PR, I'm happy to merge this!

**Pull request merged**
