### PR TITLE
IOS Redirect Wallet issue fix

### LINKED ISSUE #735: Redirect to wallet doesn't prompt the connection in iOS
**Describe the bug**
After your build in iOS, and you click on Redirect to Wallet, it redirects you to the wallet but it doesn't prompt you to connect to the app.

**Steps**
1. Use the scene [SampleLogin]
2. Build in iOS
3. Select "Redirect to wallet" option
4. Select from the dropdown the wallet that you have installed in your phone
5. Click on "Continue with Existing Wallet" button

**Expected behavior**

- User is redirected to the wallet
- Wallet prompts the user to connect the wallet to the app

**Screenshots/Video**
IMG_B1EF9304F6BA-1
Captura de pantalla 2023-11-14 a la(s) 10 42 43

**Mobile (please complete the following information):**
 - Chainsafe SDK version: [main]
 - Platform: [OS]
 - Device Type: [Real device]

**Additional context**
Discovered in https://github.com/ChainSafe/web3.unity/pull/718

### PR DESCRIPTION
**Pull request by robGG1997**
closes #735

### CODE REVIEW

**Review by sneakzttv — APPROVED** [review]

**Review by RyRy79261 — APPROVED** [review]

**Review by kantagara — APPROVED** [review]

**Comment by kantagara** [comment]
Hey yes it should be in the 2.5.4 release

**Comment by dataexcess** [comment]
> > > Hey yes it should be in the 2.5.4 release
> > 
> > 
> > Thank you yes now after trying several times it seems it worked. I had a lot of issues with it first. In the end I updated unity to latest LTS version. and I set code stripping to false and Managed stripping level to 'minimal'. I'm not sure what made it work in the end. If you can confirm that these steps are necessary I would encourage you to put them in the documentation. Great library! Thnx
> 
> Yes, code stripping to false and Managed stripping level to 'minimal' are necessary. Also, you may need to add the "-ld_classic" flag in XCode build settings, more information: [#686 (comment)](https://github.com/ChainSafe/web3.unity/issues/686#issuecomment-1781140960) (depending on your xcode version)

It's impossible to know this information by just following the SDK guide! Please add this to the docs to save headache for future ios developers.

**Comment by dataexcess** [comment]
> @dataexcess just for the testing sake, if you only updated to LTS, can you remain with the default low code stripping and set to true the engine code stripping? I would like to draw a conclusion about something. :)

ok let me try...

**Comment by dataexcess** [comment]
Ok with code stripping set to true it also works!

**Comment by dataexcess** [comment]
When I set code stripping to low it does not work anymore. Minimal seems required!

**Comment by wagenheimer** [comment]
Is this still an issue? I am experiencing the same problem with Unity 2022.3.38.

**Comment by kantagara** [comment]
> Is this still an issue? I am experiencing the same problem with Unity 2022.3.38. 

What SDK Version are you using?

**Pull request merged**
