### PR TITLE
Update UnitySampleProject to 2022 LTS

### PR DESCRIPTION
**Pull request by oleksandrchainsafe**
Updated to 2022.3.26f1

### CODE REVIEW

**Comment by oleksandrchainsafe** [comment]
@juans-chainsafe Please "Ensure all features are working as before across all platforms"

**Review by sneakzttv — APPROVED** [review]

**Review by juans-chainsafe — CHANGES_REQUESTED** [review]
I didnt finish the whole testing, but this is the feedback so far:

- Editor with web3auth + samples + logout + remember me ✅ 
- Editor with wallet connect + samples + logout + remember me  ✅ 
- Isolated Lootbox scene (without login) in editor ✅ 
- WebGL with metamask login + samples + logout ✅ 

❌ Issues:
- Ramp is not working in WebGL, neither metamask login or web3auth, loading spinner is stuck in a loop: Screenshot 2024-05-03 at 10 38 29 AM
- Samples that require sign a transaction like GetNonce, Mint or Transfer in **WebGL** with **web3auth**:  Screenshot 2024-05-03 at 12 39 12 PM
```
Invoking error handler due to
RuntimeError: null function or function signature mismatch
```

Stuff that I can't test due to previous errors:
- Countly https://github.com/ChainSafe/web3.unity/issues/880
- 3 of the Gelato samples https://github.com/ChainSafe/web3.unity/issues/881  

PENDING:
- iOS with web3auth
- iOS with wallet connect
- Empty Unity project from scratch

**Comment by juans-chainsafe** [comment]
> I didnt finish the whole testing, but this is the feedback so far:
> 
> * Editor with web3auth + samples + logout + remember me ✅
> * Editor with wallet connect + samples + logout + remember me  ✅
> * Isolated Lootbox scene (without login) in editor ✅
> * WebGL with metamask login + samples + logout ✅
> 
> ❌ Issues:
> 
> * Ramp is not working in WebGL, neither metamask login or web3auth, loading spinner is stuck in a loop: Screenshot 2024-05-03 at 10 38 29 AM
> * Samples that require sign a transaction like GetNonce, Mint or Transfer in **WebGL** with **web3auth**:  Screenshot 2024-05-03 at 12 39 12 PM
> 
> ```
> Invoking error handler due to
> RuntimeError: null function or function signature mismatch
> ```
> 
> Stuff that I can't test due to previous errors:
> 
> * Countly [Countly not working in WebGL with Package manager #880](https://github.com/ChainSafe/web3.unity/issues/880)
> * 3 of the Gelato samples [Some Gelato calls are cancelled #881](https://github.com/ChainSafe/web3.unity/issues/881)
> 
> PENDING:
> 
> * iOS with web3auth
> * iOS with wallet connect
> * Empty Unity project from scratch

iOS testing:

- iOS with web3auth + samples + logout + remember me ✅ 
- iOS with wallet connect + samples + logout + remember me ✅ 
- Ramp ✅ 

@oleksandrchainsafe weird thing is that Ramp is working in iOS but not in WebGL. And samples that require a transaction works in iOS + web3auth but they DON'T work in WebGL + web3auth

**Comment by juans-chainsafe** [comment]
Ramp issue on WebGL can be solved by doing this:

1. First make a WebGL build NOT Build And Run
2. Second go into the build directory and change/rename index.html to index.htm
3. Third use this command to start a web server for your build "C:/Program Files/Unity/Hub/Editor/2022.3.26f1/Editor/Data/MonoBleedingEdge/bin/mono.exe" "C:/Program Files/Unity/Hub/Editor/2022.3.26f1/Editor/Data/PlaybackEngines/WebGLSupport/BuildTools/SimpleWebServer.exe" "[Build Directory]" 60606 make sure the directories match yours
4. Finally navigate to http://localhost:60606/index.htm

In Mac third step should be replaces by:

1. Install python
2. Change "Compression Format" to "Gzip" in Publishing Settings
3. Enable "Decompression Fallback" in Publishing Settings
Screenshot 2024-05-10 at 11 44 56 AM
4. Run `python3 -m http.server` in the build folder
5. Go to http://localhost:8000/index.htm in the browser

**Review by juans-chainsafe — APPROVED** [review]
WebGL + Web3Auth issue was fixed with https://github.com/ChainSafe/web3.unity/pull/963
So, we are good to go!

**Review by rob1997 — APPROVED** [review]

**Pull request merged**
