### PR TITLE
Fixing Ramp Not Working with the new scene setup

### LINKED ISSUE #844: Remove traces of Ramp from the main package
**Summary**
Currently, it's a bit ugly how ramp is working and I am fully aware of it-> it is a spearate module but I still referenced it in the main scene just for the sake of making everything work across all platforms on which we support Ramp.

**Suggested features or ways to address the summary**
Rob is going to create a nice adapter pattern that we are going to utilize for injecting additional services per our (and our developers) needs.

**Motivation**
Cross-referencing modules especially those that are not shipped together is not a good idea.

**Acceptance Criteria**
- [] Have RampServiceProvider be easily drag'n' dropped in the login scene

**Blockers**
- [] Lack of the actual implementation in the main branch.

**Dependencies**
- [] This issue can be worked on only when we can actually have the interface/scriptable object on the main branch.

### PR DESCRIPTION
**Pull request by kantagara**
This closes #844 and #847 

Will also update documentation and record a new video.

### CODE REVIEW

**Comment by rob1997** [comment]
Are we just adding the ramp service adapter? we could add #if platform dependent compilation for it too since ramp currently only works on specific platforms

**Comment by kantagara** [comment]
Oh good call. I will also add two more scripts!

**Comment by kantagara** [comment]
@rob1997 added it.

**Review by rob1997 — APPROVED** [review]

**Comment by rob1997** [comment]
> @rob1997 added it.

LGTM! what's the use case for the new script? disabling GO based on available service

**Comment by kantagara** [comment]
> > @rob1997 added it.
> 
> LGTM! what's the use case for the new script? disabling GO based on available service

If you log in on main, you will see Ramp being there (in Editor), which is not supported platform. That scripts ensures that game objects that are bound to certain services will not show up in the SampleMain because that would give you errors..

**Review by sneakzttv — APPROVED** [review]
One step closer to 2.6 woo, love how you're tieing a nullcheck boolean on services into activation btw, top tier.

```
private void Awake()
    {
        gameObject.SetActive(Web3Accessor.Web3.ServiceProvider.GetService(_typesDictionary[serviceType]) != null);
    }
```

**Review by juans-chainsafe — APPROVED** [review]
Ramp working correctly!
Metamask scene ✅ 
iOS ✅ 
WebGL ✅

**Pull request merged**
