### PR TITLE
Nikola/marketplace demo

### PR DESCRIPTION
**Pull request by kantagara**
@juans-chainsafe had to strip off a large portion of the marketplace sample scene (code is still there) just so that we can demonstrate how easy it is to list and purhcase the nfts. There is marketplace browser object where you can paste your project id, marketplace id and marketplace address, that will easily help you out to retreive items from the marketplace.

### CODE REVIEW

**Review by juans-chainsafe — CHANGES_REQUESTED** [review]
merge conflicts

**Review by sneakzttv — APPROVED** [review]
Great additions, thank you for cleaning this up, conflicts RE Juans request above, otherwise good. We ran through this earlier today in the demo sprint, much nicer load speeds too.

**Review by juans-chainsafe — COMMENTED** [review]
@kantagara also, be aware that MarketplaceSampleScene is set by default to open after the login in this PR, we should put back SampleMain

**Comment by kantagara** [comment]
Closing this one in order to make the proper implementation that we already had in place.

**Pull request closed without merging**
