### PR TITLE
paste should work on webgl for all input fields 

### LINKED ISSUE #1108: Paste from clipboard not working in Marketplace verification code in WebGL
**Describe the bug**
You can't put the verification code from your clipboard in Marketplace verification code view in a WebGL build

**Steps**
1. Use the scene [SampleLogin - Connect modal]
2. Login with [Metamask]
3. Copy verification code from the email received
4. Use ctrl + V or cmd + V

**Expected behavior**
Verification code appears on the verification code input

**Screenshots/Video**
If applicable, add screenshots or screen recordings that help visualize the issue.
Screenshot 2024-08-23 at 11 13 00 AM

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [dev]
 - Platform: [WebGL]
 - Unity Version: [e.g., 2022.3.26]
 - Operating System: [Mac]

### PR DESCRIPTION
**Pull request by kantagara**
@juans-chainsafe change just the sample main scene to the one I've added - MarketplaceSampleScene

Also make sure to test out copying/pasting the private keys and the wallet address for web3auth. 
Closes #1108

### CODE REVIEW

**Comment by kantagara** [comment]
@juans-chainsafe I am dumb. Please re-check it on both webGL and iOS.

**Review by rob1997 — APPROVED** [review]

**Comment by kantagara** [comment]
Good catch, will add it.

**Review by juans-chainsafe — APPROVED** [review]
Great!

- Paste from clipboard working in verification code on WebGL ✅ (a bit annoying that in Mac you need to use ctrl + v instead of cmd + v, but is fine)
- Copy and paste address and private key still working in web3auth with WebGL ✅ 
- Paste from clipboard working in iOS as well ✅

**Review by creeppak — APPROVED** [review]
wow. good job ✅

**Comment by kantagara** [comment]
@juans-chainsafe squeezed in the support for command + v as well :)

**Pull request merged**
