### PR TITLE
Webgl fix

### LINKED ISSUE #807: network.js not updated webgl is not the selected platform
**Describe the bug**
If you save the server settings in a platform that is not WebGL and you don't have the WebGL templates yet, the network.js file is not updated because it doesnt exists yet. And when you switch to WebGL they get the default values in network.js

**Steps**
1. Delete, if you have it, the **WebGLTemplates** folder inside **Assets**
2. Save ChainSafe Server Settings
3. Switch platform to WebGL to download the templates

**Expected behavior**
network.js file contains the information saved on Server Settings before
Expected example:
```
//You can see a list of compatible EVM chains at https://chainlist.org/
window.networks = [
  {
    id: 11155111,
    label: "Sepolia ETH",
    token: "ETH",
    rpcUrl: 'https://sepolia.infura.io/v3/904006115c764661965dc0909e5ed473',
  }
]
```

**Screenshots/Video**
Actual result:
```
// Used to set the network, chains can be found at: https://chainlist.org/
// Onboard JS chain config objects, set this to your build information

// interface Chain {
//   namespace?: 'evm';
//   id: ChainId;
//   rpcUrl: string;
//   label: string;
//   token: TokenSymbol;
//   color?: string;
//   icon?: string;
//   providerConnectionInfo?: ConnectionInfo;
//   publicRpcUrl?: string;
//   blockExplorerUrl?: string;
// }

window.networks = [
  {
    id: 11155111,
    label: "Ethereum Sepolia",
    token: "Seth",
    rpcUrl: `https://sepolia.infura.io/v3/287318045c6e455ab34b81d6bcd7a65f`,
  }
]
```

**Desktop (please complete the following information):**
 - Chainsafe SDK version: [main]
 - Unity Version: [2021.3.22]
 - Operating System: Any

**Additional context**
Please add any other relevant context or information about the problem. This could include device specifications, project configuration, or any other details that might be helpful in diagnosing the issue.

### PR DESCRIPTION
**Pull request by sneakzttv**
Made the write file step happen after the database refresh.
Closes #807

### CODE REVIEW

**Review by kantagara — APPROVED** [review]

**Review by kantagara — CHANGES_REQUESTED** [review]
@sneakzttv read the issue carefully. Issue stated that network file gets overwritten when installing webgl templates. You need to store the configuration (if it exists) before installing webgl templates. Then overwrite the network file.

**Comment by kantagara** [comment]
Ignore my smart ass

**Review by kantagara — APPROVED** [review]
Tested it out, looks good!

**Comment by sneakzttv** [comment]
> @sneakzttv read the issue carefully. Issue stated that network file gets overwritten when installing webgl templates. You need to store the configuration (if it exists) before installing webgl templates. Then overwrite the network file that was placed there by webgl templates.

Sir, I test my PRs before they hit QA xD

**Pull request merged**
