### PR TITLE
Fixing Web3Auth - Gelato workflow

### LINKED ISSUE #565: Gelato not working when used with W3A
There is errors when calling samples scripts for Gelato when logged in with W3A.

### PR DESCRIPTION
**Pull request by kalambet**
Fixes #565

### CODE REVIEW

**Comment by sneakzttv** [comment]
testing

**Comment by sneakzttv** [comment]
CallWithSyncFee: Working
CallWithSyncFeeErc2771: Working
SponsorCall: Failing as no api key is present
SponsorCall2771: Failing as no api key is present

Do we have a test api key somewhere? Or a means of obtaining one?

**Comment by sneakzttv** [comment]
grabbed on off juan, checking again

**Review by sneakzttv — APPROVED** [review]
All calls completed successfully, good to go!

image

**Comment by kalambet** [comment]
There is a Gelato key hardcoded into the sources, so you can test all of that out if box.

**Comment by sneakzttv** [comment]
> There is a Gelato key hardcoded into the sources, so you can test all of that out if box.

I see an empty string hardcoded in the source, is it hidden elsewhere? Couldn't find one. Got it sorted with Juan anyway.

**Review by juans-chainsafe — APPROVED** [review]
All working in Unity editor with Web3Auth!

Just a reminder that I couldn't test it on WebGL due to the login error with web3auth
Screenshot 2023-09-07 at 16 48 11

**Pull request merged**
