### PR TITLE
Remove CsServer scripts & prefabs

### LINKED ISSUE #911: Remove CSServer and old scripts that are using it
**Summary**
The endpoints that we are using in CSServer will be deprecated, so we need to remove them from the code. The good thing is that we are not using any of the scripts in the SampleMain samples, so should we risk free.

**Suggested features or ways to address the summary**
Endpoints that will be removed:
- /evm/collection/check
- /evm/collection/create
- /evm/collection/get
- /evm/collection/getAll
- /evm/collection/getByNft
- /evm/collection/update
- /evm/collection/remove
- /evm/collection/addNFTsFromCollection
- /evm/createApproveTransaction
- /evm/createCancelNftTransaction
- /evm/createMintNFTTransaction
- /evm/createRedeemTransaction
- /evm/createListNftTransaction
- /evm/createPurchaseNftTransaction
-  /evm/getListedNfts
-  /evm/getMarketplaceData
-  /evm/getMintedNfts
-  /evm/getNftData
-  /evm/reportContent

I found these endpoints being used in:

- CSSServer.cs
- CreateApproval.cs
- GetListedCollections.cs
- GetListedNFT.cs
- ListCollections.cs
- ListNft.cs

**Motivation**
We shouldn't have code that can't be used

**Acceptance Criteria**
- None of the endpoints mentioned before should be in web3.unity, neither the scripts that were using them

**Blockers**
- We may have old game projects with an old SDK version that are using something of the NFT stuff but unlikely and not sure how to check since we don't have Datadog anymore

### PR DESCRIPTION
**Pull request by sneakzttv**
Removing unused CSServer scripts. Closes #911

### CODE REVIEW

**Comment by sneakzttv** [comment]
@juans-chainsafe should be fine as they have no implementations barring the prefabs which i already removed but please double check that there are no errors on boot and sample install.

**Review by juans-chainsafe — CHANGES_REQUESTED** [review]
@sneakzttv Im getting the following build error:

`/Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Token/Erc1155.cs(7,19): error CS0234: The type or namespace name 'Remote' does not exist in the namespace 'Scripts.EVM' (are you missing an assembly reference?`)

**Comment by sneakzttv** [comment]
should be good now, build working on my end @juans-chainsafe please test when ready

**Review by juans-chainsafe — APPROVED** [review]
Working now! I did a WebGL and iOS build as well just in case

**Pull request merged**
