### PR TITLE
feat/webgl fix & nft api

### PR DESCRIPTION
**Pull request by sneakzttv**
This fixes the webgl initialization error as well as integrating the infura api fix from @nftpixels for the allnft calls.
@juans-chainsafe & @nftpixels please review when you get time on monday <3

### CODE REVIEW

**Review by nftpixels — APPROVED** [review]
Great to see a replacement for the graph coming in! :)

**Comment by sneakzttv** [comment]
Waiting for @kalambet to attempt a solution as this isn't the way to fix a critical bug even though it's fully functional & tested.

**Review by Arshia001 — CHANGES_REQUESTED** [review]
Minified file should not be changed directly. Do we have the un-minified sources?

**Comment by RyRy79261** [comment]
@Arshia001 The one being used is from this [branch of the template repo](https://github.com/ChainSafe/web3.unity-webgl-template/tree/feat/parcel-refactor)

**Comment by Arshia001** [comment]
@RyRy79261 so if we figure out where exactly the error is, we can just make the same change in that repo, right?

**Pull request closed without merging**
