### PR TITLE
Web3Auth Initial documentation

### LINKED ISSUE #671: Create Documentation for Web3Auth Package in Unity, and the tests (SetUp method mostly) that we have created for our Web3 package.

### PR DESCRIPTION
**Pull request by RyRy79261**
closes #671

### CODE REVIEW

**Review by kalambet — CHANGES_REQUESTED** [review]
It is not necessary to document body of the tests (no need to remove what is already there, though) but it does make sense to document bodies of the `SetUp` and `TearDown` functions more where it is necessary.
There are more tests files that are missing in this PR.

**Comment by RyRy79261** [comment]
@kalambet So the test files I was pointed at were only these ones, as for any other test files, I'm not sure they're within this scope

**Comment by kalambet** [comment]
@RyRy79261 what I meant is that in the `ChainSafe.Tests` project contains beside `ProvidersSendTests.cs` that you updated also:
```
ChainlinkLootboxTests.cs
ChainsafeRPCTests.cs
Web3Util.cs
```

**Review by sneakzttv — APPROVED** [review]
everything else looks great

**Comment by RyRy79261** [comment]
@kalambet 
>  that in the ChainSafe.Tests project contains beside ProvidersSendTests.cs that you updated also:

What did you mean by this?

**Comment by kalambet** [comment]
I mean that this is the current set of your changes:
image

But Test project has 3 more files:
```
ChainlinkLootboxTests.cs
ChainsafeRPCTests.cs
Web3Util.cs
```
That needs docstrings.

**Review by kalambet — APPROVED** [review]
LGTM!

**Review by robGG1997 — APPROVED** [review]

**Pull request merged**
