### PR TITLE
Marketplace prefab v2

### PR DESCRIPTION
**Pull request by sneakzttv**
conflicts were messy, made a new branch with less file changes.

https://github.com/ChainSafe/web3.unity/assets/57473220/6885bd06-57a9-4c84-afec-bc6ea902238b

To Test:

Drop the prefab from marketplace samples into a scene with an event manager, click around, have fun, woot woot.

### CODE REVIEW

**Review by juans-chainsafe — CHANGES_REQUESTED** [review]
Im able to login with the verification code and see the first screen:
Screenshot 2024-07-10 at 6 33 49 PM

But if I enter Marketplaces for example, I see this error:
```
NullReferenceException: Object reference not set to an instance of an object
Scripts.EVM.Remote.CSServer.GetDataWithToken[T] (System.String _path, System.String _bearerToken, System.Int32 offset, System.Int32 pageSize) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Remote/CSServer.cs:49)
Scripts.EVM.Marketplace.Marketplace.GetProjectMarketplaces (System.String bearerToken) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity.marketplace/Runtime/Scripts/Marketplace/Marketplace.cs:31)
ChainSafe.Gaming.Marketplace.BrowseMarketplaceManager.GetProjectMarketplaces () (at Assets/Samples/web3.unity SDK Marketplace/2.6.1/Marketplace Samples/Scripts/BrowseMarketplaceManager.cs:62)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

```

And if I try to create a new marketplace:
```
NullReferenceException: Object reference not set to an instance of an object
Scripts.EVM.Marketplace.Marketplace.CreateMarketplace (System.String _bearerToken, System.String _name, System.String _description, System.Boolean _whitelisting) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity.marketplace/Runtime/Scripts/Marketplace/Marketplace.cs:334)
ChainSafe.Gaming.Marketplace.CreateMarketplaceManager.CreateMarketplace (System.String marketplaceName, System.String marketplaceDescription, System.Boolean marketplaceWhiteListing) (at Assets/Samples/web3.unity SDK Marketplace/2.6.1/Marketplace Samples/Scripts/CreateMarketplaceManager.cs:51)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

**Comment by sneakzttv** [comment]
> Im able to login with the verification code and see the first screen: Screenshot 2024-07-10 at 6 33 49 PM
> 
> But if I enter Marketplaces for example, I see this error:
> 
> ```
> NullReferenceException: Object reference not set to an instance of an object
> Scripts.EVM.Remote.CSServer.GetDataWithToken[T] (System.String _path, System.String _bearerToken, System.Int32 offset, System.Int32 pageSize) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Remote/CSServer.cs:49)
> Scripts.EVM.Marketplace.Marketplace.GetProjectMarketplaces (System.String bearerToken) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity.marketplace/Runtime/Scripts/Marketplace/Marketplace.cs:31)
> ChainSafe.Gaming.Marketplace.BrowseMarketplaceManager.GetProjectMarketplaces () (at Assets/Samples/web3.unity SDK Marketplace/2.6.1/Marketplace Samples/Scripts/BrowseMarketplaceManager.cs:62)
> System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
> UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
> UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
> ```
> 
> And if I try to create a new marketplace:
> 
> ```
> NullReferenceException: Object reference not set to an instance of an object
> Scripts.EVM.Marketplace.Marketplace.CreateMarketplace (System.String _bearerToken, System.String _name, System.String _description, System.Boolean _whitelisting) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity.marketplace/Runtime/Scripts/Marketplace/Marketplace.cs:334)
> ChainSafe.Gaming.Marketplace.CreateMarketplaceManager.CreateMarketplace (System.String marketplaceName, System.String marketplaceDescription, System.Boolean marketplaceWhiteListing) (at Assets/Samples/web3.unity SDK Marketplace/2.6.1/Marketplace Samples/Scripts/CreateMarketplaceManager.cs:51)
> System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
> UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
> UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
> UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
> ```

hmm...i'll find out why

**Comment by sneakzttv** [comment]
should work now @juans-chainsafe succeeding on my end.

**Review by oleksandrchainsafe — APPROVED** [review]
Approving.

We'd need to rework this to separate the logic provided for devs from the logic provided for players though. The missing logic for players should be added to the MarketplaceClient of the core solution. The logic for devs can reside as editor scripts in the unity package, so it's not getting included in the builds.

**Comment by juans-chainsafe** [comment]
> should work now @juans-chainsafe succeeding on my end.

Im still having some issues, I see the new loading screen which is great, but doesnt disappear and a error in the console appears:

```
NullReferenceException: Object reference not set to an instance of an object
Scripts.EVM.Remote.CSServer.GetDataWithToken[T] (System.String _path, System.String _bearerToken, System.Int32 offset, System.Int32 pageSize) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity/Runtime/Scripts/EVM/Remote/CSServer.cs:49)
Scripts.EVM.Marketplace.Marketplace.GetProjectMarketplaces (System.String bearerToken) (at /Users/juanmanuelspoleti/Desktop/workspace/web3.unity/Packages/io.chainsafe.web3-unity.marketplace/Runtime/Scripts/Marketplace/Marketplace.cs:31)
ChainSafe.Gaming.Marketplace.BrowseMarketplaceManager.GetProjectMarketplaces () (at Assets/Samples/web3.unity SDK Marketplace/2.6.1/Marketplace Samples/Scripts/BrowseMarketplaceManager.cs:62)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <e307bbb467104258887a104f6151f183>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:153)
UnityEngine.UnitySynchronizationContext.Exec () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:83)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)

```
Screenshot 2024-07-11 at 9 35 22 AM

This is my scene, is not saved or anything
Screenshot 2024-07-11 at 9 35 41 AM

**Comment by sneakzttv** [comment]
will check first thing monday, i think the token error is web3authwallet related, maybe something is sticking around.

**Comment by sneakzttv** [comment]
image
image

hmm it operates fine for me, maybe something is sticking around, reset your repo and try with a fresh clone for me please.

**Comment by juans-chainsafe** [comment]
> image image
> 
> hmm it operates fine for me, maybe something is sticking around, reset your repo and try with a fresh clone for me please. The images above were taken from a fresh clone too so i could be sure.

still getting the token error, do I need to save the scene in a particular directory? I just drag and drop the MarketplaceLogin.prefab and add the event system. Im able to login and logout

**Comment by sneakzttv** [comment]
nah, that should be correct, will dm you and we'll figure out why xD

**Comment by sneakzttv** [comment]
most issues fixed, some minor things left, will fix in next PR, merging so we can move forward with unity downgrade.

**Pull request merged**
