### PR TITLE
Importable Sample Project

### PR DESCRIPTION
**Pull request by robGG1997**
+ Moved sample project to an importable sample from Web3.Unity package
+ Added Initialization fixes to ProjectConfigUtilities, it can now create resource directory if it doesn't exist
+ Implemented SceneIndexer which basically adds sample scenes to Build Settings
+ moving forward when making changes to the Sample Project files (scripts and prefabs) in the editor you should also make those changes to files in the sample folder in `src\UnityPackages\io.chainsafe.web3-unity\Samples~\Web3.Unity` 
image

### CODE REVIEW

**Review by juans-chainsafe — APPROVED** [review]
Looks good! Samples are working in Unity editor and WebGL

**Review by kalambet — APPROVED** [review]
LGTM!
Re-imported and tested!

**Review by sneakzttv — APPROVED** [review]

**Comment by sneakzttv** [comment]
Can we do this via yaml file or something instead of needing to manually update in 2 places at once?

**Comment by robGG1997** [comment]
> Can we do this via yaml file or something instead of needing to manually update in 2 places at once?

You can set up a symbolic link (mklink for windows) for the files.

**Pull request merged**
